/* eslint-disable */
// @ts-ignore
import { Suspense } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import HelloWorld from "@components/HelloWorld";
import Matches from "@components/Matches";
import User from "@components/User";
import Header from "@components/Header";
import FCM from "@components/FCM";
import Toast from "@components/Toast";

const Home = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Suspense fallback={<div>Loading...</div>}>
          <Header />
        </Suspense>
        <Toast />
        <FCM />

        <HelloWorld />
        <Suspense fallback={<article>Loading User...</article>}>
          <User />
        </Suspense>

        <Matches />
      </main>
    </div>
  );
};

export default Home;
